version: "3.8"
services:
  mysql:
    image: mysql:latest
    ports:
      - "8083:3306"
    volumes:
      - ./test-sql-2:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 192bmsz@
      MYSQL_USER: Kreator
      MYSQL_PASSWORD: 192bmsz@
      MYSQL_DATABASE: familyDock
    networks:
          - common-network
  adminer:
    image: adminer
    restart: always
    ports:
      - "8040:8040"
    networks:
      - common-network
  app:
    depends_on:
      - mysql
    build: ./
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      SPRING_APPLICATION_JSON: '{
        "server": {
          "port": 8000
        },
        "spring": {
          "database": {
            "driver": {
              "classname": "com.mysql.cj.jdbc.Driver"
            }
          },
          "datasource": {
            "url": "jdbc:mysql://localhost:3306/familyDock?createDatabaseIfNotExist=true&useSSL=false",
            "username": "Kreator",
            "password": "192bmsz@"
          },
          "jpa": {
            "database-platform": "org.hibernate.dialect.MySQLDialect",
            "hibernate": {
              "ddl-auto": "update"
            }
          }
        }
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
networks:
  common-network:
    driver: bridge
volumes:
   db:



